# Generated by Django 4.1.5 on 2023-02-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoden', '0002_rename_title_operation_name_operation_cipher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='cipher',
        ),
        migrations.AddField(
            model_name='operation',
            name='cipher',
            field=models.ManyToManyField(to='cryptoden.cipher'),
        ),
    ]
