# Generated by Django 4.1.5 on 2023-02-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoden', '0003_remove_operation_cipher_operation_cipher'),
    ]

    operations = [
        migrations.AddField(
            model_name='cipher',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
