# Generated by Django 4.1.5 on 2023-04-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoden', '0006_cryptodenuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptodenuser',
            name='name',
        ),
    ]
