# Generated by Django 4.1.5 on 2023-04-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoden', '0007_remove_cryptodenuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptodenuser',
            name='username',
        ),
    ]
