# Generated by Django 4.1.5 on 2023-04-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoden', '0008_remove_cryptodenuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptodenuser',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
