# Generated by Django 4.1.5 on 2023-01-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_background',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to=''),
        ),
    ]
