# Generated by Django 4.1.5 on 2023-01-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile_profile_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_page_background', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
