# Generated by Django 4.1.5 on 2023-01-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='line1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='line2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='line3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
