# Generated by Django 4.1.5 on 2023-01-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
