# Generated by Django 4.1.5 on 2023-01-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_project_short_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='desc',
            new_name='long_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_desc',
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
