# Generated by Django 4.1.5 on 2023-01-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_contact_id_alter_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='landing_page_background',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_background',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/uploads/images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/uploads/images/'),
        ),
    ]
