# Generated by Django 4.1.5 on 2023-01-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_page_landing_page_background'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='skill',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='created',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.AddField(
            model_name='skill',
            name='stack',
            field=models.CharField(blank=True, choices=[('front-end', 'Front-end'), ('back-end', 'Back-end')], editable=False, max_length=20),
        ),
    ]
