# Generated by Django 4.1.5 on 2023-02-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_page_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='fourofour',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
