# Generated by Django 4.1.5 on 2023-02-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_page_fourofour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_background',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
