# Generated by Django 4.1.5 on 2023-02-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_project_demo_link_alter_project_source_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='link_preview_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
