# Generated by Django 4.1.5 on 2023-04-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_page_link_preview_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='long_bio',
            new_name='profile_card_bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='short_bio',
        ),
        migrations.AlterField(
            model_name='profile',
            name='line1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='line2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='line3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
